=encoding utf8

=head1 NAME

Module::Install::Package - Package Support for Module::Install

=head1 SYNOPSIS

    use inc::Module::Install; pkg;

=head1 DESCRIPTION

This Module::Install plugin attempts to make your C<Makefile.PL> as small as
possible. It figures out most of the basics for you, but still let's you
override everything.

=head1 STATUS

This module is at a "proving concepts" phase. It is not ready for general use.

=head1 CONCEPTS

Modules packaged with Package, put their extra package config info in the pkg/
directory. Files in this directory never get shipped in the final installable
distribution.

Some of the things Package is doing:

  * Show how to make a small, one-line Makefile.PL
  * Put overrides in pkg/makefile.pl
  * Removing author-only Module::Install plugins from the dist.
  * Removing the need for maintaining MANIFEST related files.
  * Adding a pkg/plugins.pl file that gets run by authors so they know which
    Makefile.PL plugins they need to have installed, to hack on the source
    repository.

=head1 AUTHOR

Ingy döt Net <ingy@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2011. Ingy döt Net.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

See http://www.perl.com/perl/misc/Artistic.html

=cut
